---
apiVersion: v1
kind: Service
metadata:
  name: helloweb-backend
  labels:
    app: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
    # pop: green
  ports:
  - port: 80
    targetPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: helloweb-blue
  labels:
    app: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
    pop: blue
  ports:
  - port: 80
    targetPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: helloweb-green
  labels:
    app: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
    pop: green
  ports:
  - port: 80
    targetPort: 8080


